function [cfg, result, fullprop] = run_rect_e2_spec_scaled_caseE()
% run_rect_e2_spec_scaled_caseE Run scaled industrial e^-2 rectangular CaseE.
%
% This case keeps the RD/Point2P initial phase and existing propagation model.
% The MRAF target is defined by scaled 90%, 50%, and 13.5% rectangular
% iso-intensity contours. Outside 13.5% is don't-care with weak suppression.

close all; clc;
project_root = fileparts(mfilename('fullpath'));
addpath(project_root);
addpath(fullfile(project_root, 'config'));
addpath(fullfile(project_root, 'src'));
addpath(fullfile(project_root, 'src', 'mraf'));

variant = struct('variant_name', "CaseE_rect_e2_spec_scaled", ...
    'preset_name', "CaseE_rect_e2_spec_scaled", ...
    'artifact_group', "rect_e2_spec_scaled", ...
    'target_mode', "rect_e2_spec_scaled", ...
    'method', "WGS-MRAF", ...
    'use_wgs', true, ...
    'wgs_exponent', 0.08, ...
    'n_iter', 20, ...
    'phase_blend', 0.20, ...
    'use_three_region_projection', true, ...
    'transition_cap_blend', 0.35, ...
    'free_factor', 1.00, ...
    'outer_factor', 0.95);

[cfg, result, fullprop] = run_mraf_one(variant);
print_caseE_summary(cfg, result, fullprop);
write_caseE_summary_csv(cfg, result, fullprop);
end

function print_caseE_summary(cfg, result, fullprop)
m = result.mraf.metrics;
fprintf('\nCaseE_rect_e2_spec_scaled summary\n');
fprintf('Artifact: %s\n', cfg.save_root);
fprintf('Measured size90  x/y = %.3f / %.3f um\n', m.measured_size90_x_um, m.measured_size90_y_um);
fprintf('Measured size50  x/y = %.3f / %.3f um\n', m.measured_size50_x_um, m.measured_size50_y_um);
fprintf('Measured size135 x/y = %.3f / %.3f um\n', m.measured_size135_x_um, m.measured_size135_y_um);
fprintf('TW 13.5-90      x/y = %.3f / %.3f um\n', m.transition_width_135_90_x_um, m.transition_width_135_90_y_um);
fprintf('RMS 90 region = %.6g, e2 efficiency = %.6g\n', m.rms_uniformity_90_region, m.e2_diffraction_efficiency);
fprintf('Shoulder peak 90-50 = %.6g, 50-13.5 = %.6g\n', m.shoulder_peak_90_50, m.shoulder_peak_50_135);
fprintf('FULL RMS 90 region = %.6g, e2 efficiency = %.6g\n', fullprop.mraf_metrics.rms_uniformity_90_region, fullprop.mraf_metrics.e2_diffraction_efficiency);
end

function write_caseE_summary_csv(cfg, result, fullprop)
m = result.mraf.metrics;
fm = fullprop.mraf_metrics;
summary = table(string(cfg.mraf.variant_name), ...
    m.measured_size90_x_um, m.measured_size90_y_um, ...
    m.measured_size50_x_um, m.measured_size50_y_um, ...
    m.measured_size135_x_um, m.measured_size135_y_um, ...
    m.transition_width_135_90_x_um, m.transition_width_135_90_y_um, ...
    m.rms_uniformity_90_region, m.e2_diffraction_efficiency, ...
    m.shoulder_peak_90_50, m.shoulder_peak_50_135, ...
    fm.measured_size90_x_um, fm.measured_size90_y_um, ...
    fm.measured_size50_x_um, fm.measured_size50_y_um, ...
    fm.measured_size135_x_um, fm.measured_size135_y_um, ...
    fm.transition_width_135_90_x_um, fm.transition_width_135_90_y_um, ...
    fm.rms_uniformity_90_region, fm.e2_diffraction_efficiency, ...
    'VariableNames', {'variant','ideal_size90_x_um','ideal_size90_y_um','ideal_size50_x_um','ideal_size50_y_um', ...
    'ideal_size135_x_um','ideal_size135_y_um','ideal_transition_135_90_x_um','ideal_transition_135_90_y_um', ...
    'ideal_rms_uniformity_90_region','ideal_e2_diffraction_efficiency','ideal_shoulder_peak_90_50','ideal_shoulder_peak_50_135', ...
    'full_size90_x_um','full_size90_y_um','full_size50_x_um','full_size50_y_um','full_size135_x_um','full_size135_y_um', ...
    'full_transition_135_90_x_um','full_transition_135_90_y_um','full_rms_uniformity_90_region','full_e2_diffraction_efficiency'});
out = fullfile(cfg.save_root, 'summary.csv');
writetable(summary, out);
fprintf('Summary CSV: %s\n', out);
end
