function [cfg, result, fullprop] = run_mraf_three_region_target_one()
% run_mraf_three_region_target_one Run one true three-region MRAF case.
close all; clc;
project_root = fileparts(mfilename('fullpath'));
addpath(project_root);
addpath(fullfile(project_root, 'config'));
addpath(fullfile(project_root, 'src'));
addpath(fullfile(project_root, 'src', 'mraf'));

variant = struct( ...
    'variant_name', "three_region_outer030_yscale1022", ...
    'preset_name', "three_region_mraf", ...
    'artifact_group', "three_region_mraf", ...
    'target_mode', "rd_derived", ...
    'target_edge_mode', "pivot50", ...
    'pivot50_inner_power', 0.75, ...
    'pivot50_outer_power', 1.25, ...
    'target_x_scale', 1.0, ...
    'target_y_scale', 1.022, ...
    'free_threshold', 0.135, ...
    'edge_low_threshold', 0.135, ...
    'guard_fraction', 1.5, ...
    'use_three_region_projection', true, ...
    'free_factor', 1.0, ...
    'outer_factor', 0.3, ...
    'n_iter', 10, ...
    'rd_target_gamma', 1.0, ...
    'mraf_factor', 1.0, ...
    'phase_blend', 0.25, ...
    'method', "WGS-MRAF", ...
    'use_wgs', true, ...
    'wgs_exponent', 0.20, ...
    'y_free_reservoir_enable', false, ...
    'wgs_y_edge_damping_enable', false);

[cfg, result, fullprop] = run_mraf_one(variant);
summary_one_case(cfg, result, fullprop);
end

function summary_one_case(cfg, result, fullprop)
m = result.mraf.metrics;
fm = fullprop.mraf_metrics;
fprintf('\nThree-region one-case summary\n');
fprintf('Artifact: %s\n', cfg.save_root);
fprintf('IDEAL size50 %.3f x %.3f um; size13.5 %.3f x %.3f um; TW %.3f x %.3f um\n', ...
    m.size50_x_um, m.size50_y_um, m.size13p5_x_um, m.size13p5_y_um, m.transition_13p5_90_x_um, m.transition_13p5_90_y_um);
fprintf('IDEAL shoulder %.6g x %.6g; core_rms %.6g; outer_tail %.6g x %.6g; true_side_lobe %.6g x %.6g has %g/%g pos %.3f/%.3f um\n', ...
    m.shoulder_peak_x, m.shoulder_peak_y, m.core_rms, m.outer_tail_peak_x_rel_to_core, m.outer_tail_peak_y_rel_to_core, ...
    m.true_side_lobe_peak_x_rel_to_core, m.true_side_lobe_peak_y_rel_to_core, m.has_true_side_lobe_x, m.has_true_side_lobe_y, ...
    m.true_side_lobe_pos_x_um, m.true_side_lobe_pos_y_um);
fprintf('FULL  size50 %.3f x %.3f um; shoulder %.6g x %.6g; core_rms %.6g; true_side_lobe %.6g x %.6g has %g/%g\n', ...
    fm.size50_x_um, fm.size50_y_um, fm.shoulder_peak_x, fm.shoulder_peak_y, fm.core_rms, ...
    fm.true_side_lobe_peak_x_rel_to_core, fm.true_side_lobe_peak_y_rel_to_core, fm.has_true_side_lobe_x, fm.has_true_side_lobe_y);
end
